# Nome do projeto
spring.application.name=smartwallet

# Configuração de conexão com o PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/vmg_wallet
spring.datasource.username=postgres
spring.datasource.password=1!Acesso#9
spring.datasource.driverClassName=org.postgresql.Driver

# Configurações do Hibernate / JPA
# 'update' faz o Spring Boot criar as tabelas automaticamente se elas não existirem
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostra as consultas SQL no terminal do VS Code (ótimo para testar e ver se está funcionando)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true